database:
  host: "%DATABASE_HOST%"
  port: "%DATABASE_PORT%"
  name: "%DATABASE_NAME%"
  user: "%DATABASE_USER%"
  password: "%DATABASE_PASSWORD%"

application:
  host: "localhost"
  port: 3000
  timezone: "Europe/Warsaw"
  secret: "%APPLICATION_SECRET%"
  corsOrigin: "http://localhost:4200"
  tokenExpirationTime: "7d"

jobs:
  closeSkippedWorkoutsEnabled: true
  closeUnfinishedWorkoutsEnabled: true
  closeSkippedWorkoutsCronDefinition: "0 0 * * *"
  closeUnfinishedWorkoutsCronDefinition: "0 0 * * *"